/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import DAO.DAOException;
import DAO.UsuarioDAO;
import DAO_MySQL.MySQLUsuarioDAO;
import Entidades.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ronal
 */
public class cambiarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form cambiarContraseña
     */
    private Usuario usuario;
    utils Utils = new utils();
    private boolean mostrarContraseña = false;

    public cambiarContraseña() {
        initComponents();
    }

    public cambiarContraseña(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        lblUsuario.setText("Bienvenido de nuevo " + usuario.getNombreUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblViewPass2 = new javax.swing.JLabel();
        txtConfirmarContraseña = new javax.swing.JPasswordField();
        btnChangePass = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        lblViewPass = new javax.swing.JLabel();
        lblChangePass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 260, 20));

        lblViewPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/ClosePass.png"))); // NOI18N
        lblViewPass2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewPass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewPass2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewPass2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewPass2MouseExited(evt);
            }
        });
        getContentPane().add(lblViewPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        txtConfirmarContraseña.setText("CONFIRME SU CONTRASEÑA");
        txtConfirmarContraseña.setBorder(null);
        txtConfirmarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmarContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 240, 30));

        btnChangePass.setBackground(new java.awt.Color(60, 9, 108));
        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/changePass.change.png"))); // NOI18N
        btnChangePass.setBorder(null);
        btnChangePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 473, -1, 40));

        txtContraseña.setText("INGRESE SU CONTRASEÑA");
        txtContraseña.setBorder(null);
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 240, 30));

        lblViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/ClosePass.png"))); // NOI18N
        lblViewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewPassMouseExited(evt);
            }
        });
        getContentPane().add(lblViewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        lblChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/RECUPERAR CONTRASEÑA.png"))); // NOI18N
        getContentPane().add(lblChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConfirmarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmarContraseñaActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        String nueva = new String(txtContraseña.getPassword());
        String confirmar = new String(txtConfirmarContraseña.getPassword());

        if (nueva.isEmpty() || confirmar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete ambos campos.");
            return;
        }

        if (!nueva.equals(confirmar)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
            return;
        }

        try {
            UsuarioDAO usuarioDAO = new MySQLUsuarioDAO();
            usuario.setContraseña(nueva); // Asignamos la nueva contraseña al objeto
            usuarioDAO.actualizar(usuario); // Suponiendo que tienes este método
            JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente.");
            Inicio in = new Inicio();
            Utils.centrarPantalla(in);
            this.dispose();
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar contraseña:\n" + ex.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(cambiarContraseña.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnChangePassActionPerformed

    private void lblViewPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPassMouseClicked
        if (mostrarContraseña) {
            txtContraseña.setEchoChar('*'); // oculta caracteres
            lblViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/ClosePass.png")));
            mostrarContraseña = false;
        } else {
            txtContraseña.setEchoChar((char) 0); // muestra caracteres
            lblViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/OpenPass.png")));
            mostrarContraseña = true;
        }
    }//GEN-LAST:event_lblViewPassMouseClicked

    private void lblViewPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPassMouseEntered

    }//GEN-LAST:event_lblViewPassMouseEntered

    private void lblViewPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPassMouseExited

    }//GEN-LAST:event_lblViewPassMouseExited

    private void lblViewPass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPass2MouseClicked
        if (mostrarContraseña) {
            txtConfirmarContraseña.setEchoChar('*'); // oculta caracteres
            lblViewPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/ClosePass.png")));
            mostrarContraseña = false;
        } else {
            txtConfirmarContraseña.setEchoChar((char) 0); // muestra caracteres
            lblViewPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/OpenPass.png")));
            mostrarContraseña = true;
        }
    }//GEN-LAST:event_lblViewPass2MouseClicked

    private void lblViewPass2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPass2MouseEntered

    }//GEN-LAST:event_lblViewPass2MouseEntered

    private void lblViewPass2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPass2MouseExited

    }//GEN-LAST:event_lblViewPass2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambiarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JLabel lblChangePass;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblViewPass;
    private javax.swing.JLabel lblViewPass2;
    private javax.swing.JPasswordField txtConfirmarContraseña;
    private javax.swing.JPasswordField txtContraseña;
    // End of variables declaration//GEN-END:variables
}
