/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import DAO.DAOException;
import DAO.UsuarioDAO;
import DAO_MySQL.MySQLUsuarioDAO;
import Entidades.Usuario;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author ronal
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    private boolean mostrarContraseña = false;

    public Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewPass = new javax.swing.JLabel();
        lblViewPass2 = new javax.swing.JLabel();
        txtConfirmarContraseña = new javax.swing.JPasswordField();
        txtContraseña = new javax.swing.JPasswordField();
        btnRegistrarseYa = new javax.swing.JButton();
        lblMensaje1 = new javax.swing.JLabel();
        lblAcceso = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lblRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/ClosePass.png"))); // NOI18N
        lblViewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewPassMouseExited(evt);
            }
        });
        getContentPane().add(lblViewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        lblViewPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/ClosePass.png"))); // NOI18N
        lblViewPass2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewPass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewPass2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewPass2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewPass2MouseExited(evt);
            }
        });
        getContentPane().add(lblViewPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

        txtConfirmarContraseña.setText("CONFIRME SU CONTRASEÑA");
        txtConfirmarContraseña.setBorder(null);
        txtConfirmarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmarContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 240, 20));

        txtContraseña.setText("INGRESE SU CONTRASEÑA");
        txtContraseña.setBorder(null);
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 240, 20));

        btnRegistrarseYa.setBackground(new java.awt.Color(60, 9, 108));
        btnRegistrarseYa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/RegistrarseYa.png"))); // NOI18N
        btnRegistrarseYa.setBorder(null);
        btnRegistrarseYa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarseYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseYaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarseYa, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 543, 310, 40));

        lblMensaje1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/registrar.yesaccount.png"))); // NOI18N
        getContentPane().add(lblMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, -1));

        lblAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/registrar.Acceso.png"))); // NOI18N
        lblAcceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAccesoMouseClicked(evt);
            }
        });
        getContentPane().add(lblAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, -1, -1));

        txtNombreUsuario.setText("Ingrese un nombre");
        txtNombreUsuario.setBorder(null);
        txtNombreUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 262, 280, 20));

        txtCorreo.setText("Ingrese su email");
        txtCorreo.setBorder(null);
        txtCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 332, 280, 20));

        lblRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/REGISTRO.png"))); // NOI18N
        getContentPane().add(lblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblViewPass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPass2MouseClicked
        if (mostrarContraseña) {
            txtConfirmarContraseña.setEchoChar('*'); // oculta caracteres
            lblViewPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/ClosePass.png")));
            mostrarContraseña = false;
        } else {
            txtConfirmarContraseña.setEchoChar((char) 0); // muestra caracteres
            lblViewPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/OpenPass.png")));
            mostrarContraseña = true;
        }
    }//GEN-LAST:event_lblViewPass2MouseClicked

    private void lblViewPass2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPass2MouseEntered

    }//GEN-LAST:event_lblViewPass2MouseEntered

    private void lblViewPass2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPass2MouseExited

    }//GEN-LAST:event_lblViewPass2MouseExited

    private void lblViewPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPassMouseClicked
        if (mostrarContraseña) {
            txtContraseña.setEchoChar('*'); // oculta caracteres
            lblViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/ClosePass.png")));
            mostrarContraseña = false;
        } else {
            txtContraseña.setEchoChar((char) 0); // muestra caracteres
            lblViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figma/OpenPass.png")));
            mostrarContraseña = true;
        }
    }//GEN-LAST:event_lblViewPassMouseClicked

    private void lblViewPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPassMouseEntered

    }//GEN-LAST:event_lblViewPassMouseEntered

    private void lblViewPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPassMouseExited

    }//GEN-LAST:event_lblViewPassMouseExited

    private void txtConfirmarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmarContraseñaActionPerformed

    private void lblAccesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAccesoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAccesoMouseClicked

    private void btnRegistrarseYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseYaActionPerformed
        String nombreUsuario = txtNombreUsuario.getText().trim();
        String correo = txtCorreo.getText().trim();
        String pass = new String(txtContraseña.getPassword());
        String confirmPass = new String(txtConfirmarContraseña.getPassword());

        // Validaciones básicas
        if (nombreUsuario.isEmpty() || correo.isEmpty() || pass.isEmpty() || confirmPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos.");
            return;
        }

        if (!pass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
            return;
        }

        try {
            Usuario nuevo = new Usuario();
            nuevo.setNombreUsuario(nombreUsuario);
            nuevo.setContraseña(pass);
            nuevo.setEmail(correo);
            nuevo.setRol("Cliente");

            UsuarioDAO dao = new MySQLUsuarioDAO(); // <- lanza SQLException
            dao.insertar(nuevo);

            JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.");
            this.dispose();
            new Bienvenida().setVisible(true);

        } catch (DAOException | SQLException ex) { // <-- Aquí añades SQLException
            JOptionPane.showMessageDialog(this, "❌ Error al registrar usuario:\n" + ex.getMessage());
        }

    }//GEN-LAST:event_btnRegistrarseYaActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarseYa;
    private javax.swing.JLabel lblAcceso;
    private javax.swing.JLabel lblMensaje1;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblViewPass;
    private javax.swing.JLabel lblViewPass2;
    private javax.swing.JPasswordField txtConfirmarContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
